# Generated by Django 4.2.25 on 2025-10-28 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordencompraingrediente',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='ordenventa',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ordenventa',
            name='productos',
        ),
        migrations.AlterUniqueTogether(
            name='receta',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='receta',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimo_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_producto',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_maximo',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='ultimo_registro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='DetalleOrdenVenta',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='OrdenCompraIngrediente',
        ),
        migrations.DeleteModel(
            name='OrdenVenta',
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
