# Generated by Django 4.2.25 on 2025-11-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movimientostock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('codigo_empleado', models.CharField(help_text='ID único del empleado/cajero', max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar si ya no labora')),
            ],
            options={
                'verbose_name': 'Cajero',
                'verbose_name_plural': 'Cajeros',
                'ordering': ['nombre'],
            },
        ),
    ]
